objects=\
box_filter.o\
color_distance_squared.o\
compute_cost.o\
compute_cost_color.o\
compute_cost_gradient.o\
compute_disparity_maps.o\
compute_weight.o\
covariance.o\
detect_occlusion.o\
dmag5_downsample_image.o\
dmag5_downsample_image_dimensions.o\
dmag5_downsample_image_int.o\
dmag5_downsample_rgb_image.o\
dmag5_downsample_rgb_image_int.o\
dmag5_error_handler.o\
fast_cost_volume_filter.o\
fill_occlusion_left_right.o\
fill_occlusion_right_left.o\
gaussian_blur_image.o\
gradient_x.o\
inverse_sym_3x3.o\
median.o\
median_histo.o\
normalize_image.o\
print_weight_image.o\
rgb_to_grayscale.o\
smooth_occlusion_weighted_median.o\
weighted_histo.o\
weighted_median.o
